Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.10.13", virtualbox__intnet: "intnet"
  #config.vm.hostname = "weko3.example.org"
  config.disksize.size = "200GB"


  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  if Vagrant.has_plugin?("vagrant-vbguest")
    # set auto_update to false, if you do NOT want to check the correct
    config.vbguest.auto_update = true
  end

  config.vm.network "forwarded_port", guest: 80, host: 8085, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 443, host: 8445, host_ip: "127.0.0.1"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = 'all'
    ansible.host_key_checking = false
  end
end
