Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define :weko3_a do | weko3_a |
    weko3_a.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "intnet"
    #config.vm.hostname = "weko3.example.org"
    weko3_a.disksize.size = "200GB"

    weko3_a.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    if Vagrant.has_plugin?("vagrant-vbguest")
      # set auto_update to false, if you do NOT want to check the correct
      weko3_a.vbguest.auto_update = true
    end

    weko3_a.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 5501, host: 5501, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 5601, host: 5601, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 15672, host: 15672, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 8080, host: 8888, host_ip: "127.0.0.1"
    weko3_a.vm.network "forwarded_port", guest: 25401, host: 25401, host_ip: "127.0.0.1"
	weko3_a.vm.network "forwarded_port", guest: 22, host: 2220, id: "ssh"
  
    weko3_a.vm.provider "virtualbox" do |vb|
      vb.memory = "6148"
    end

      weko3_a.vm.provision "ansible" do |ansible|
        ansible.playbook = "../site.yml"
        ansible.inventory_path = "hosts"
        ansible.limit = 'all'
        ansible.host_key_checking = false
      end
  end

  config.vm.define :weko3_b do | weko3_b |
    weko3_b.vm.network "private_network", ip: "192.168.10.11", virtualbox__intnet: "intnet"
    #config.vm.hostname = "weko3.example.org"
    weko3_b.disksize.size = "200GB"


    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    if Vagrant.has_plugin?("vagrant-vbguest")
      # set auto_update to false, if you do NOT want to check the correct
      weko3_b.vbguest.auto_update = true
    end

    weko3_b.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 443, host: 8444, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 5501, host: 5502, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 5601, host: 5602, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 15672, host: 15673, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 8080, host: 8889, host_ip: "127.0.0.1"
    weko3_b.vm.network "forwarded_port", guest: 25401, host: 25402, host_ip: "127.0.0.1"
	weko3_b.vm.network "forwarded_port", guest: 22, host: 2221, id: "ssh"

    weko3_b.vm.provider "virtualbox" do |vb|
      vb.memory = "6148"
    end

      weko3_b.vm.provision "ansible" do |ansible|
        ansible.playbook = "../site.yml"
        ansible.inventory_path = "hosts"
        ansible.limit = 'all'
        ansible.host_key_checking = false
      end
  end
end
